name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Get source code
      uses: actions/checkout@v4
    - name: Login no Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          nmuianga/primeira-pipeline:latest
          nmuianga/primeira-pipeline:v1.0.0